
apiVersion: apps/v1

kind: Deployment

metadata:
  name: smart-disaster-response-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: smart-disaster-response-system

  template:

    metadata:
      labels:
        app: smart-disaster-response-system

    spec:

      containers:

      - name: smart-disaster-response-system

        image: smart-disaster-response-system:latest

        ports:
        - containerPort: 8080
